### O Objetivo é fazer a previsão do preço ###

In [1]:
import pandas as pd

In [2]:
base = pd.read_csv("../datasets/autos.csv", encoding= 'ISO-8859-1')

In [3]:
base

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21
5,2016-04-04 17:36:23,BMW_316i___e36_Limousine___Bastlerfahrzeug__Ex...,privat,Angebot,650,test,limousine,1995,manuell,102,3er,150000,10,benzin,bmw,ja,2016-04-04 00:00:00,0,33775,2016-04-06 19:17:07
6,2016-04-01 20:48:51,Peugeot_206_CC_110_Platinum,privat,Angebot,2200,test,cabrio,2004,manuell,109,2_reihe,150000,8,benzin,peugeot,nein,2016-04-01 00:00:00,0,67112,2016-04-05 18:18:39
7,2016-03-21 18:54:38,VW_Derby_Bj_80__Scheunenfund,privat,Angebot,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein,2016-03-21 00:00:00,0,19348,2016-03-25 16:47:58
8,2016-04-04 23:42:13,Ford_C___Max_Titanium_1_0_L_EcoBoost,privat,Angebot,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN,2016-04-04 00:00:00,0,94505,2016-04-04 23:42:13
9,2016-03-17 10:53:50,VW_Golf_4_5_tuerig_zu_verkaufen_mit_Anhaengerk...,privat,Angebot,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN,2016-03-17 00:00:00,0,27472,2016-03-31 17:17:06
10,2016-03-26 19:54:18,Mazda_3_1.6_Sport,privat,Angebot,2000,control,limousine,2004,manuell,105,3_reihe,150000,12,benzin,mazda,nein,2016-03-26 00:00:00,0,96224,2016-04-06 10:45:34
11,2016-04-07 10:06:22,Volkswagen_Passat_Variant_2.0_TDI_Comfortline,privat,Angebot,2799,control,kombi,2005,manuell,140,passat,150000,12,diesel,volkswagen,ja,2016-04-07 00:00:00,0,57290,2016-04-07 10:25:17
12,2016-03-15 22:49:09,"VW_Passat_Facelift_35i__""7Sitzer""",privat,Angebot,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN,2016-03-15 00:00:00,0,37269,2016-04-01 13:16:16
13,2016-03-21 21:37:40,VW_PASSAT_1.9_TDI_131_PS_LEDER,privat,Angebot,2500,control,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein,2016-03-21 00:00:00,0,90762,2016-03-23 02:50:54
14,2016-03-21 12:57:01,Nissan_Navara_2.5DPF_SE4x4_Klima_Sitzheizg_Blu...,privat,Angebot,17999,control,suv,2011,manuell,190,navara,70000,3,diesel,nissan,nein,2016-03-21 00:00:00,0,4177,2016-04-06 07:45:42
15,2016-03-11 21:39:15,KA_Lufthansa_Edition_450_VB,privat,Angebot,450,test,kleinwagen,1910,NaN,0,ka,5000,0,benzin,ford,NaN,2016-03-11 00:00:00,0,24148,2016-03-19 08:46:47
16,2016-04-01 12:46:46,Polo_6n_1_4,privat,Angebot,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN,2016-04-01 00:00:00,0,38871,2016-04-01 12:46:46
17,2016-03-20 10:25:19,Renault_Twingo_1.2_16V_Aut.,privat,Angebot,1750,control,kleinwagen,2004,automatik,75,twingo,150000,2,benzin,renault,nein,2016-03-20 00:00:00,0,65599,2016-04-06 13:16:07
18,2016-03-23 15:48:05,Ford_C_MAX_2.0_TDCi_DPF_Titanium,privat,Angebot,7550,test,bus,2007,manuell,136,c_max,150000,6,diesel,ford,nein,2016-03-23 00:00:00,0,88361,2016-04-05 18:45:11
19,2016-04-01 22:55:47,Mercedes_Benz_A_160_Classic_Klima,privat,Angebot,1850,test,bus,2004,manuell,102,a_klasse,150000,1,benzin,mercedes_benz,nein,2016-04-01 00:00:00,0,49565,2016-04-05 22:46:05
20,2016-04-01 19:56:48,Volkswagen_Scirocco_1.4_TSI_Sport,privat,Angebot,10400,control,coupe,2009,manuell,160,scirocco,100000,4,benzin,volkswagen,nein,2016-04-01 00:00:00,0,75365,2016-04-05 16:45:49
21,2016-03-27 11:38:00,BMW_530i_TÜV_7/17_Scheckheftgepflegt_sehr_gute...,privat,Angebot,3699,test,limousine,2002,automatik,231,5er,150000,7,benzin,bmw,nein,2016-03-27 00:00:00,0,68309,2016-04-07 06:44:26
22,2016-03-23 14:52:51,Opel_Meriva_1.Hand_TÜV_3.2018,privat,Angebot,2900,test,NaN,2018,manuell,90,meriva,150000,5,benzin,opel,nein,2016-03-23 00:00:00,0,49716,2016-03-31 01:16:33
23,2016-03-12 19:43:07,Stadtflitzer,privat,Angebot,450,test,kleinwagen,1997,manuell,50,arosa,150000,5,benzin,seat,nein,2016-03-12 00:00:00,0,9526,2016-03-21 01:46:11
24,2016-03-13 20:40:49,MERCEDES_200E__TÜV_04/2016,privat,Angebot,500,test,limousine,1990,manuell,118,andere,150000,10,benzin,mercedes_benz,ja,2016-03-13 00:00:00,0,35390,2016-03-13 20:40:49
25,2016-03-18 21:44:09,BMW_530d_touring_Vollausstattung_NAVI,privat,Angebot,2500,control,kombi,2002,automatik,193,5er,150000,9,diesel,bmw,ja,2016-03-18 00:00:00,0,73765,2016-03-18 21:44:09
26,2016-03-10 19:38:18,Citroen_C4_Grand_Picasso.,privat,Angebot,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein,2016-03-10 00:00:00,0,31139,2016-03-16 09:16:46
27,2016-03-07 12:51:23,Honda_Civic_1.4_i_VTEC_Comfort,privat,Angebot,6900,test,limousine,2008,manuell,99,civic,60000,11,benzin,honda,nein,2016-03-07 00:00:00,0,12621,2016-03-26 09:44:53
28,2016-03-09 11:56:38,Volkswagen_T3_andere,privat,Angebot,1990,test,bus,1981,manuell,50,transporter,5000,1,benzin,volkswagen,nein,2016-03-09 00:00:00,0,87471,2016-03-10 07:44:33
29,2016-03-08 19:55:19,Fiat_Punto_1.2,privat,Angebot,690,test,kleinwagen,2003,manuell,60,punto,150000,3,benzin,fiat,nein,2016-03-08 00:00:00,0,86199,2016-03-09 11:45:28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371498,2016-03-11 15:50:38,Opel_Vectra_Edition_100,privat,Angebot,699,control,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,NaN,2016-03-11 00:00:00,0,65936,2016-03-17 12:44:29
371499,2016-03-08 13:52:00,OPEL_CORSA_B__ECO_SWING__TÜV_1/17_8fach_Bereif...,privat,Angebot,600,control,kleinwagen,1998,manuell,54,corsa,150000,1,benzin,opel,nein,2016-03-08 00:00:00,0,24850,2016-03-13 00:16:40
371500,2016-03-21 23:40:49,Volkswagen_Golf_1.4_TSI_BlueMotion_Technology_...,privat,Angebot,20400,test,limousine,2014,automatik,150,golf,30000,9,benzin,volkswagen,nein,2016-03-21 00:00:00,0,38470,2016-04-07 04:17:32
371501,2016-03-26 18:36:54,Chrysler_Voyager,privat,Angebot,3900,test,bus,2003,automatik,174,voyager,150000,7,benzin,chrysler,nein,2016-03-26 00:00:00,0,34320,2016-04-06 09:16:04
371502,2016-04-01 12:59:21,Audi_A4_Avant_1.8,privat,Angebot,1600,test,kombi,1998,manuell,125,a4,150000,2,benzin,audi,nein,2016-04-01 00:00:00,0,34414,2016-04-07 09:44:29
371503,2016-04-01 01:55:58,Subaru_Justy_1.3,privat,Angebot,1700,control,kleinwagen,1999,manuell,68,justy,70000,11,benzin,subaru,nein,2016-03-31 00:00:00,0,90439,2016-04-07 04:16:26
371504,2016-03-07 17:06:35,220_cdi_Benz,privat,Angebot,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN,2016-03-07 00:00:00,0,61169,2016-03-08 21:28:38
371505,2016-04-03 19:56:57,Opel_Astra_1.6_Caravan_Selection,privat,Angebot,800,test,kombi,2000,manuell,101,astra,150000,11,benzin,opel,ja,2016-04-03 00:00:00,0,58730,2016-04-05 20:45:39
371506,2016-03-20 18:47:59,Volkswagen_Golf_1.9_TDI_DPF_Goal_Rentnerfzg._1...,privat,Angebot,5900,test,limousine,2006,manuell,105,golf,150000,9,diesel,volkswagen,nein,2016-03-20 00:00:00,0,1217,2016-04-07 02:44:27
371507,2016-03-16 17:06:19,Gepflegter_Audi_a4_2.0tdi_xenon_ahk_klima_sche...,privat,Angebot,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN,2016-03-16 00:00:00,0,56472,2016-03-18 11:30:17
371508,2016-04-02 16:43:27,Opel_Astra_1.8,privat,Angebot,1400,control,limousine,2001,manuell,125,astra,150000,2,benzin,opel,nein,2016-04-02 00:00:00,0,23820,2016-04-06 15:18:04
371509,2016-03-11 23:40:32,LT_35_DIESEL_Gruene_Plakette....letzte_Gelegen...,privat,Angebot,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein,2016-03-11 00:00:00,0,87700,2016-03-12 14:16:51
371510,2016-03-06 21:11:23,Mercedes_benz_e_klasse_avangarde_220_cdi_grune...,privat,Angebot,6500,test,limousine,2003,automatik,145,e_klasse,150000,3,diesel,mercedes_benz,nein,2016-03-05 00:00:00,0,60437,2016-03-12 12:18:05
371511,2016-03-31 18:50:37,Audi_A3_1.8_T_Attraction,privat,Angebot,1999,control,limousine,1997,manuell,150,a3,150000,12,benzin,audi,nein,2016-03-31 00:00:00,0,4275,2016-04-06 12:46:41
371512,2016-03-25 18:48:06,Mercedes_Benz_E_400_CDI_Avantgarde,privat,Angebot,5000,test,limousine,2003,automatik,260,e_klasse,150000,12,diesel,mercedes_benz,ja,2016-03-25 00:00:00,0,90473,2016-04-07 00:44:51
371513,2016-03-21 15:36:22,Seat_Leon_1.9_TDI_4/5_Tueren,privat,Angebot,4400,control,limousine,2008,manuell,105,leon,150000,7,diesel,seat,nein,2016-03-21 00:00:00,0,45896,2016-04-06 15:45:01
371514,2016-04-04 11:45:16,Renault_1_4_ltr.16_V_Megane_Cabrio,privat,Angebot,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN,2016-04-04 00:00:00,0,88477,2016-04-06 12:44:52
371515,2016-03-09 11:36:55,Skoda_Fabia_Kombi_1.4,privat,Angebot,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN,2016-03-09 00:00:00,0,18246,2016-04-04 08:15:30
371516,2016-04-04 09:57:12,Volkswagen_Lupo_1.0,privat,Angebot,1490,control,kleinwagen,1998,manuell,50,lupo,150000,9,benzin,volkswagen,nein,2016-04-04 00:00:00,0,48653,2016-04-06 11:17:13
371517,2016-03-28 13:48:07,Volkswagen_Golf_2.0_TDI_DPF_Team,privat,Angebot,7900,test,limousine,2010,manuell,140,golf,150000,7,diesel,volkswagen,nein,2016-03-28 00:00:00,0,75223,2016-04-02 18:16:20
371518,2016-04-02 20:37:03,Bmw_320_D_DPF_Touring_!!!,privat,Angebot,3999,test,kombi,2005,manuell,3,3er,150000,5,diesel,bmw,nein,2016-04-02 00:00:00,0,81825,2016-04-06 20:47:12
371519,2016-03-09 13:37:43,Alfa_Romeo_159_Jtdm_1.9_150_ps_13_600_km_top_voll,privat,Angebot,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein,2016-03-09 00:00:00,0,51371,2016-03-13 01:44:13
371520,2016-03-19 19:53:49,turbo_defekt,privat,Angebot,3200,control,limousine,2004,manuell,225,leon,150000,5,benzin,seat,ja,2016-03-19 00:00:00,0,96465,2016-03-19 20:44:43
371521,2016-03-27 20:36:20,Opel_Zafira_1.6_Elegance_TÜV_12/16,privat,Angebot,1150,control,bus,2000,manuell,0,zafira,150000,3,benzin,opel,nein,2016-03-27 00:00:00,0,26624,2016-03-29 10:17:23
371522,2016-03-21 09:50:58,Mitsubishi_Cold,privat,Angebot,0,control,NaN,2005,manuell,0,colt,150000,7,benzin,mitsubishi,ja,2016-03-21 00:00:00,0,2694,2016-03-21 10:42:49
371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52
371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

In [4]:
base.columns

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'kilometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

In [5]:
base['offerType'].value_counts()

Angebot    371516
Gesuch         12
Name: offerType, dtype: int64

#### As colunas abaixo foram retiradas por que existe uma discrepancia muito grande entre os resultados, por exemplo a coluna offerType tem dois possíveis valores, e um deles teve 12 e o outro 371516 ####

In [6]:
base = base.drop('name', axis=1)
base = base.drop('seller', axis=1)
base = base.drop('offerType', axis=1)
base = base.drop('dateCrawled', axis=1)
base = base.drop('dateCreated', axis=1)
base = base.drop('nrOfPictures', axis=1)
base = base.drop('postalCode', axis=1)
base = base.drop('lastSeen', axis=1)

In [7]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371528 entries, 0 to 371527
Data columns (total 12 columns):
price                  371528 non-null int64
abtest                 371528 non-null object
vehicleType            333659 non-null object
yearOfRegistration     371528 non-null int64
gearbox                351319 non-null object
powerPS                371528 non-null int64
model                  351044 non-null object
kilometer              371528 non-null int64
monthOfRegistration    371528 non-null int64
fuelType               338142 non-null object
brand                  371528 non-null object
notRepairedDamage      299468 non-null object
dtypes: int64(5), object(7)
memory usage: 34.0+ MB

In [8]:
# quantos valores estão os o valor de preço abaixo de 20 
i1 = base.loc[base.price <= 20]
i1.count().sum()

126719

In [9]:
base = base.loc[base.price > 10]

In [10]:
i2 = base.loc[base.price > 350000]
i2

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
1846,579000,control,coupe,1980,manuell,277,andere,20000,12,benzin,bmw,nein
10649,420000,control,coupe,2004,manuell,483,911,50000,4,benzin,porsche,nein
14663,11111111,control,coupe,2003,manuell,64,polo,150000,2,benzin,volkswagen,NaN
16889,1000000,control,kombi,1998,NaN,0,mondeo,150000,0,benzin,ford,ja
20143,1250000,test,coupe,2016,manuell,500,911,5000,3,benzin,porsche,nein
20746,12345678,test,NaN,1995,NaN,0,NaN,150000,0,NaN,volkswagen,NaN
21467,9999999,control,coupe,1967,manuell,215,911,50000,10,benzin,porsche,nein
26327,600000,test,coupe,2016,manuell,500,911,5000,3,benzin,porsche,nein
38445,999999,test,bus,1981,manuell,70,transporter,150000,1,benzin,volkswagen,NaN
39625,12345678,control,NaN,2018,manuell,95,v40,150000,6,NaN,volvo,nein
41980,2995000,control,coupe,2005,NaN,630,NaN,5000,7,benzin,sonstige_autos,nein
45055,2795000,control,coupe,2016,NaN,963,NaN,5000,3,NaN,sonstige_autos,nein
45833,1000000,control,coupe,1981,manuell,300,911,150000,1,benzin,porsche,nein
53507,1000000,test,suv,1992,manuell,69,andere,100000,0,benzin,suzuki,nein
54295,10000000,control,bus,2007,manuell,143,5_reihe,150000,2,diesel,mazda,nein
54507,11111111,test,andere,1953,manuell,20,NaN,150000,5,NaN,audi,nein
56973,99999999,control,limousine,2002,manuell,131,mondeo,150000,1,NaN,ford,NaN
57594,1111111,test,NaN,1995,manuell,71,astra,150000,5,benzin,opel,NaN
69726,999999,test,andere,1960,manuell,9999,NaN,150000,0,NaN,mercedes_benz,NaN
69747,99999999,control,bus,2006,NaN,0,andere,150000,0,diesel,mercedes_benz,NaN
77185,500000,test,coupe,2004,manuell,435,NaN,30000,7,benzin,sonstige_autos,nein
77520,99999999,control,limousine,1999,automatik,224,s_klasse,150000,9,benzin,mercedes_benz,NaN
78265,820000,control,cabrio,2016,NaN,674,NaN,5000,3,benzin,sonstige_autos,nein
78480,1250000,test,coupe,2016,manuell,500,911,5000,3,benzin,porsche,nein
82700,395000,test,cabrio,1972,manuell,194,NaN,100000,1,benzin,sonstige_autos,nein
85047,911911,test,cabrio,1967,manuell,160,911,5000,12,benzin,porsche,nein
87799,27322222,control,limousine,2014,manuell,163,c4,40000,2,diesel,citroen,NaN
90853,11111111,control,NaN,2018,NaN,0,NaN,150000,0,NaN,bmw,NaN
91106,9999999,test,limousine,1996,manuell,380,a4,60000,5,benzin,audi,nein
100851,700000,test,coupe,2016,NaN,0,911,5000,3,NaN,porsche,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
301198,999999,control,NaN,2015,NaN,0,NaN,5000,2,NaN,sonstige_autos,NaN
303287,399997,test,coupe,2010,manuell,620,911,20000,10,benzin,porsche,nein
306469,1000000,control,coupe,1985,manuell,75,polo,150000,0,benzin,volkswagen,ja
310924,12345678,test,kleinwagen,1997,manuell,45,NaN,150000,7,benzin,volkswagen,NaN
312109,1000000,test,NaN,2000,NaN,0,a3,150000,0,NaN,audi,NaN
312909,999999,test,kombi,2009,manuell,101,focus,125000,4,benzin,ford,nein
316200,1300000,control,coupe,1992,NaN,0,NaN,50000,12,NaN,sonstige_autos,nein
318143,11111111,test,NaN,1995,NaN,0,NaN,150000,0,NaN,volkswagen,NaN
325589,99999999,test,limousine,1983,manuell,70,golf,150000,3,NaN,volkswagen,nein
328614,390000,test,cabrio,2001,manuell,400,z_reihe,5000,4,benzin,bmw,nein
330117,466000,test,coupe,1993,manuell,549,andere,5000,5,benzin,jaguar,nein
332028,11111111,control,NaN,1995,NaN,116,golf,150000,6,benzin,volkswagen,NaN
332531,999999,control,NaN,1985,NaN,0,NaN,150000,0,diesel,chevrolet,NaN
333699,1600000,test,coupe,2005,NaN,0,NaN,10000,4,NaN,sonstige_autos,nein
336623,368000,test,cabrio,2010,automatik,625,andere,30000,3,benzin,mercedes_benz,nein
337851,487000,test,coupe,2015,automatik,500,NaN,5000,8,NaN,porsche,nein
338415,11111111,test,NaN,2000,NaN,120,polo,125000,0,benzin,volkswagen,NaN
344196,745000,control,coupe,2016,manuell,500,911,5000,3,benzin,porsche,nein
347435,9999999,test,NaN,2000,manuell,75,golf,150000,0,benzin,volkswagen,ja
358868,10000000,control,kombi,2002,manuell,0,NaN,150000,7,diesel,bmw,nein
359083,999990,test,limousine,1985,manuell,111,jetta,150000,12,benzin,volkswagen,ja
360768,440000,control,coupe,2015,NaN,0,NaN,5000,8,NaN,sonstige_autos,nein
361451,10010011,test,NaN,2000,NaN,0,NaN,150000,0,NaN,sonstige_autos,NaN
362782,99999999,test,NaN,1995,NaN,0,passat,150000,0,benzin,volkswagen,NaN
363434,10000000,test,kombi,1996,manuell,90,NaN,150000,0,benzin,volkswagen,ja
364171,3890000,test,coupe,2006,NaN,799,NaN,5000,7,NaN,sonstige_autos,nein
365461,599000,control,coupe,1980,manuell,377,andere,5000,3,benzin,bmw,nein
366653,99999999,control,cabrio,1996,manuell,192,3er,150000,0,NaN,bmw,NaN
366861,3895000,test,coupe,2006,NaN,799,NaN,5000,4,benzin,sonstige_autos,nein
367041,1600000,test,coupe,2005,NaN,625,NaN,10000,4,benzin,sonstige_autos,nein

In [11]:
base = base.loc[base.price < 350000]
base.count().sum()

4147366

In [12]:
# verificando se existem valores nulos no atributo vehicleType
base.loc[pd.isnull(base.vehicleType)]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
16,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN
22,2900,test,NaN,2018,manuell,90,meriva,150000,5,benzin,opel,nein
26,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein
31,899,control,NaN,2016,manuell,60,clio,150000,6,benzin,renault,NaN
35,350,test,NaN,2016,manuell,75,golf,150000,4,benzin,volkswagen,nein
37,1500,test,NaN,2016,NaN,0,kangoo,150000,1,diesel,renault,nein
48,7750,control,NaN,2017,manuell,80,golf,100000,1,benzin,volkswagen,NaN
51,2000,control,NaN,2017,manuell,90,punto,150000,11,diesel,fiat,ja
52,1400,control,NaN,2016,manuell,55,andere,5000,1,NaN,hyundai,NaN
58,2399,test,NaN,2018,manuell,64,andere,125000,3,NaN,seat,nein
66,10900,test,NaN,2017,manuell,101,astra,50000,3,NaN,opel,nein
72,2300,control,NaN,1997,manuell,150,5er,150000,3,NaN,bmw,nein
78,800,test,NaN,2000,manuell,90,golf,150000,2,diesel,volkswagen,NaN
81,150,control,NaN,2016,manuell,75,astra,150000,3,benzin,opel,ja
94,250,control,NaN,2000,NaN,60,ka,150000,0,NaN,ford,NaN
96,8390,test,NaN,2009,NaN,0,insignia,150000,0,NaN,opel,NaN
111,900,test,NaN,1995,manuell,90,civic,150000,3,benzin,honda,NaN
130,8000,control,NaN,2009,manuell,0,golf,100000,10,benzin,volkswagen,nein
134,3390,test,NaN,2000,NaN,0,3er,150000,2,NaN,bmw,NaN
150,150,control,NaN,1985,NaN,0,100,150000,4,benzin,audi,NaN
152,300,control,NaN,2005,manuell,0,punto,40000,9,NaN,fiat,ja
160,14500,control,NaN,2017,manuell,136,sportage,125000,5,diesel,kia,nein
168,1200,control,NaN,2018,manuell,75,astra,150000,0,NaN,opel,nein
186,3000,control,NaN,2016,automatik,75,fabia,150000,0,benzin,skoda,NaN
202,2800,control,NaN,2018,manuell,75,twingo,125000,12,NaN,renault,nein
206,1999,test,NaN,2016,manuell,110,almera,150000,9,diesel,nissan,NaN
224,2100,test,NaN,2017,manuell,0,zafira,150000,12,diesel,opel,NaN
226,850,control,NaN,1985,manuell,54,caddy,150000,0,diesel,volkswagen,NaN
231,900,test,NaN,2017,manuell,60,corsa,150000,0,benzin,opel,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
371146,10980,test,NaN,2018,manuell,75,NaN,20000,1,NaN,volkswagen,nein
371150,1000,control,NaN,2017,manuell,54,NaN,125000,2,NaN,hyundai,nein
371189,350,test,NaN,2000,manuell,50,ibiza,150000,5,NaN,seat,nein
371197,2950,test,NaN,2016,manuell,0,picanto,80000,7,benzin,kia,nein
371210,3700,control,NaN,2016,manuell,90,golf,150000,4,diesel,volkswagen,NaN
371216,1750,test,NaN,1995,NaN,0,NaN,100000,12,NaN,sonstige_autos,NaN
371242,250,control,NaN,2016,manuell,0,3er,150000,5,benzin,bmw,ja
371243,4900,test,NaN,2017,manuell,69,polo,150000,12,diesel,volkswagen,NaN
371245,600,control,NaN,2016,manuell,170,vectra,150000,0,benzin,opel,ja
371252,395,control,NaN,2016,manuell,60,golf,150000,12,benzin,volkswagen,NaN
371258,3600,test,NaN,2017,manuell,86,transit,150000,5,diesel,ford,NaN
371261,299,test,NaN,2016,manuell,60,astra,150000,4,benzin,opel,ja
371274,400,test,NaN,2000,NaN,0,twingo,150000,0,NaN,renault,NaN
371286,1000,control,NaN,2017,manuell,101,a4,150000,9,NaN,audi,NaN
371309,1500,control,NaN,1995,NaN,0,NaN,150000,0,NaN,volkswagen,NaN
371316,3000,control,NaN,2016,manuell,0,colt,150000,8,diesel,mitsubishi,nein
371349,1350,test,NaN,2016,manuell,0,clk,150000,8,NaN,mercedes_benz,ja
371354,2140,test,NaN,2018,manuell,80,fiesta,150000,6,NaN,ford,nein
371359,8700,test,NaN,2009,NaN,0,2_reihe,90000,8,benzin,peugeot,NaN
371370,790,test,NaN,1990,manuell,0,andere,150000,1,benzin,renault,NaN
371380,9000,test,NaN,2008,NaN,0,1er,125000,0,NaN,bmw,NaN
371407,1250,test,NaN,2018,NaN,0,corsa,150000,0,benzin,opel,NaN
371444,5000,control,NaN,2017,manuell,120,andere,150000,7,NaN,citroen,ja
371460,3500,control,NaN,1995,NaN,0,polo,150000,0,NaN,volkswagen,NaN
371493,3299,test,NaN,2005,automatik,0,outlander,150000,4,benzin,mitsubishi,NaN
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371504,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN
371509,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein
371519,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [13]:
# verificando qual o tipo de veiculo que mais aparece 
base.vehicleType.value_counts()

limousine     93614
kleinwagen    78014
kombi         65921
bus           29699
cabrio        22509
coupe         18386
suv           14477
andere         3125
Name: vehicleType, dtype: int64

In [14]:
# verificando valores nulos do gearbox (caixa de cambío) 
base.loc[pd.isnull(base.gearbox)]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
15,450,test,kleinwagen,1910,NaN,0,ka,5000,0,benzin,ford,NaN
16,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN
32,245,test,limousine,1994,NaN,0,golf,150000,2,benzin,volkswagen,nein
37,1500,test,NaN,2016,NaN,0,kangoo,150000,1,diesel,renault,nein
70,1200,test,coupe,2001,NaN,0,astra,150000,0,NaN,opel,NaN
94,250,control,NaN,2000,NaN,60,ka,150000,0,NaN,ford,NaN
96,8390,test,NaN,2009,NaN,0,insignia,150000,0,NaN,opel,NaN
114,350,test,kleinwagen,1998,NaN,0,corsa,150000,2,benzin,opel,NaN
134,3390,test,NaN,2000,NaN,0,3er,150000,2,NaN,bmw,NaN
150,150,control,NaN,1985,NaN,0,100,150000,4,benzin,audi,NaN
156,6799,control,kleinwagen,2009,NaN,60,NaN,20000,5,benzin,volkswagen,nein
166,1495,control,kombi,2001,NaN,64,NaN,150000,9,diesel,volkswagen,NaN
191,14000,test,limousine,2008,NaN,235,NaN,150000,0,NaN,bmw,nein
203,3200,control,kombi,2006,NaN,0,a3,150000,11,diesel,audi,nein
214,2250,control,kleinwagen,2001,NaN,41,fortwo,150000,10,diesel,smart,nein
240,3750,control,NaN,2005,NaN,75,golf,150000,0,NaN,volkswagen,NaN
245,130,test,kombi,1998,NaN,0,e_klasse,150000,0,NaN,mercedes_benz,NaN
288,2400,test,cabrio,2001,NaN,115,golf,150000,8,benzin,volkswagen,nein
297,1250,control,NaN,2017,NaN,0,espace,150000,8,benzin,renault,NaN
306,2390,test,NaN,2016,NaN,83,jazz,150000,12,benzin,honda,nein
307,1450,control,NaN,2017,NaN,0,a_klasse,150000,8,benzin,mercedes_benz,NaN
308,1699,control,limousine,1999,NaN,75,astra,150000,12,benzin,opel,NaN
318,200,control,NaN,2009,NaN,0,NaN,10000,0,NaN,sonstige_autos,NaN
321,350,test,NaN,2017,NaN,0,corsa,150000,0,benzin,opel,NaN
367,1050,test,NaN,2018,NaN,0,golf,150000,0,NaN,volkswagen,NaN
371,6250,test,limousine,2003,NaN,299,a6,150000,3,benzin,audi,NaN
372,10000,control,bus,1976,NaN,0,transporter,5000,0,benzin,volkswagen,NaN
376,49500,test,cabrio,2013,NaN,0,NaN,10000,6,benzin,sonstige_autos,nein
404,3400,control,NaN,2018,NaN,0,astra,150000,8,benzin,opel,nein
406,2350,test,NaN,2006,NaN,0,c1,5000,0,andere,citroen,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
370796,550,test,NaN,1990,NaN,0,80,5000,0,NaN,audi,NaN
370800,3200,test,bus,1995,NaN,0,transporter,150000,1,diesel,volkswagen,nein
370988,11000,control,bus,2006,NaN,0,vito,150000,11,diesel,mercedes_benz,nein
371029,7900,test,bus,2009,NaN,140,NaN,125000,7,diesel,sonstige_autos,nein
371050,800,control,NaN,1970,NaN,0,andere,150000,0,NaN,trabant,NaN
371056,999,control,NaN,2018,NaN,0,golf,150000,8,NaN,volkswagen,nein
371059,3500,test,kleinwagen,2005,NaN,0,a_klasse,150000,0,NaN,mercedes_benz,NaN
371068,750,control,kleinwagen,2001,NaN,0,andere,150000,0,benzin,hyundai,NaN
371075,850,test,coupe,2000,NaN,0,astra,150000,11,benzin,opel,NaN
371088,1000,control,NaN,2005,NaN,0,astra,150000,0,NaN,opel,NaN
371099,200,control,NaN,1910,NaN,0,NaN,5000,0,benzin,sonstige_autos,NaN
371142,250,test,cabrio,1997,NaN,0,punto,150000,0,NaN,fiat,NaN
371144,210,test,kleinwagen,1997,NaN,60,polo,150000,0,NaN,volkswagen,NaN
371181,3590,control,coupe,2000,NaN,0,3er,150000,10,NaN,bmw,nein
371216,1750,test,NaN,1995,NaN,0,NaN,100000,12,NaN,sonstige_autos,NaN
371274,400,test,NaN,2000,NaN,0,twingo,150000,0,NaN,renault,NaN
371279,250,test,kleinwagen,1994,NaN,75,golf,150000,6,benzin,volkswagen,nein
371299,13500,test,suv,2005,NaN,0,xc_reihe,150000,0,diesel,volvo,NaN
371309,1500,control,NaN,1995,NaN,0,NaN,150000,0,NaN,volkswagen,NaN
371359,8700,test,NaN,2009,NaN,0,2_reihe,90000,8,benzin,peugeot,NaN
371375,4300,control,kleinwagen,2009,NaN,0,ibiza,150000,3,benzin,seat,nein
371380,9000,test,NaN,2008,NaN,0,1er,125000,0,NaN,bmw,NaN
371407,1250,test,NaN,2018,NaN,0,corsa,150000,0,benzin,opel,NaN
371414,399,test,andere,1994,NaN,1103,3er,150000,0,NaN,bmw,NaN
371440,3500,control,kleinwagen,2001,NaN,75,corsa,90000,4,benzin,opel,nein
371443,3300,control,kombi,2006,NaN,0,touran,150000,7,diesel,volkswagen,NaN
371460,3500,control,NaN,1995,NaN,0,polo,150000,0,NaN,volkswagen,NaN
371486,350,control,kleinwagen,1996,NaN,65,punto,150000,0,NaN,fiat,NaN
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [15]:
base.gearbox.value_counts()

manuell      266547
automatik     75508
Name: gearbox, dtype: int64

In [16]:
base.loc[pd.isnull(base.model)]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
1,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja
83,350,control,kleinwagen,1997,manuell,54,NaN,150000,3,NaN,fiat,ja
139,1450,control,limousine,1992,manuell,136,NaN,150000,0,NaN,audi,nein
156,6799,control,kleinwagen,2009,NaN,60,NaN,20000,5,benzin,volkswagen,nein
165,500,control,kleinwagen,1999,manuell,0,NaN,150000,0,benzin,renault,nein
166,1495,control,kombi,2001,NaN,64,NaN,150000,9,diesel,volkswagen,NaN
191,14000,test,limousine,2008,NaN,235,NaN,150000,0,NaN,bmw,nein
199,1200,test,coupe,1990,manuell,45,NaN,150000,0,benzin,volkswagen,NaN
268,450,control,NaN,2016,manuell,0,NaN,150000,3,benzin,mitsubishi,nein
285,1500,control,coupe,1994,manuell,116,NaN,150000,8,NaN,audi,nein
318,200,control,NaN,2009,NaN,0,NaN,10000,0,NaN,sonstige_autos,NaN
320,1600,test,kombi,1999,manuell,0,NaN,150000,6,benzin,bmw,nein
365,5500,test,kleinwagen,2012,manuell,68,NaN,40000,12,NaN,peugeot,nein
373,300,control,kleinwagen,2001,manuell,0,NaN,150000,5,benzin,peugeot,ja
376,49500,test,cabrio,2013,NaN,0,NaN,10000,6,benzin,sonstige_autos,nein
427,13950,control,andere,2011,manuell,140,NaN,60000,11,diesel,alfa_romeo,nein
446,3950,test,kleinwagen,2004,automatik,5,NaN,70000,5,diesel,sonstige_autos,nein
450,1300,control,NaN,2017,manuell,150,NaN,150000,10,NaN,volkswagen,nein
451,5800,control,bus,2007,manuell,105,NaN,150000,11,diesel,volkswagen,ja
458,1950,control,NaN,2017,manuell,0,NaN,150000,7,benzin,volkswagen,nein
563,2600,control,NaN,2005,NaN,0,NaN,125000,0,NaN,chevrolet,NaN
577,50,test,NaN,1985,NaN,0,NaN,150000,11,NaN,trabant,NaN
612,3800,test,cabrio,2005,manuell,109,NaN,100000,12,benzin,peugeot,NaN
644,1600,test,kleinwagen,2002,manuell,64,NaN,150000,2,benzin,volkswagen,nein
658,7400,test,cabrio,2003,automatik,192,NaN,150000,8,NaN,bmw,nein
672,2200,test,limousine,1995,automatik,299,NaN,150000,5,NaN,audi,ja
677,1900,control,limousine,2000,manuell,125,NaN,150000,5,benzin,mitsubishi,nein
678,15000,test,coupe,1971,NaN,0,NaN,5000,4,NaN,sonstige_autos,nein
690,9900,test,suv,2000,automatik,250,NaN,150000,4,lpg,sonstige_autos,nein
698,5900,control,kombi,2004,manuell,150,NaN,150000,2,diesel,mercedes_benz,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
370819,400,control,kombi,1998,manuell,105,NaN,150000,7,benzin,volvo,NaN
370836,900,control,NaN,2017,manuell,101,NaN,150000,6,NaN,opel,NaN
370890,250,control,kleinwagen,1997,manuell,66,NaN,150000,5,benzin,sonstige_autos,NaN
370903,650,test,NaN,2000,manuell,150,NaN,150000,7,NaN,audi,nein
370952,9800,control,kleinwagen,2013,manuell,90,NaN,50000,4,NaN,renault,NaN
370968,11690,control,kombi,2005,automatik,224,NaN,150000,5,diesel,audi,nein
371001,2800,control,coupe,2003,manuell,163,NaN,150000,7,benzin,citroen,NaN
371004,5000,test,limousine,2006,manuell,175,NaN,125000,12,benzin,sonstige_autos,nein
371029,7900,test,bus,2009,NaN,140,NaN,125000,7,diesel,sonstige_autos,nein
371060,2200,test,suv,1994,manuell,124,NaN,150000,0,benzin,ford,nein
371065,18500,test,limousine,2009,automatik,190,NaN,150000,10,diesel,audi,nein
371099,200,control,NaN,1910,NaN,0,NaN,5000,0,benzin,sonstige_autos,NaN
371102,1599,test,kleinwagen,2002,manuell,75,NaN,150000,0,benzin,ford,NaN
371110,1670,control,NaN,2018,manuell,0,NaN,90000,0,benzin,renault,nein
371121,1500,control,bus,1984,manuell,0,NaN,150000,5,diesel,mercedes_benz,NaN
371146,10980,test,NaN,2018,manuell,75,NaN,20000,1,NaN,volkswagen,nein
371150,1000,control,NaN,2017,manuell,54,NaN,125000,2,NaN,hyundai,nein
371196,42000,control,limousine,2012,automatik,564,NaN,50000,3,benzin,sonstige_autos,nein
371203,6000,test,kleinwagen,2008,manuell,155,NaN,150000,5,benzin,sonstige_autos,nein
371214,30900,control,cabrio,1960,automatik,250,NaN,100000,7,benzin,sonstige_autos,nein
371216,1750,test,NaN,1995,NaN,0,NaN,100000,12,NaN,sonstige_autos,NaN
371220,200,control,kleinwagen,1998,manuell,37,NaN,150000,4,benzin,volkswagen,ja
371223,4300,test,kleinwagen,2008,automatik,0,NaN,150000,3,NaN,honda,NaN
371309,1500,control,NaN,1995,NaN,0,NaN,150000,0,NaN,volkswagen,NaN
371388,5000,control,limousine,2002,automatik,170,NaN,150000,0,benzin,audi,nein
371399,560,control,kleinwagen,2001,automatik,170,NaN,90000,0,benzin,fiat,ja
371476,9400,control,kombi,2007,manuell,200,NaN,150000,4,diesel,sonstige_autos,ja
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371509,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [17]:
base.loc[base.model.isnull()]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
1,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja
83,350,control,kleinwagen,1997,manuell,54,NaN,150000,3,NaN,fiat,ja
139,1450,control,limousine,1992,manuell,136,NaN,150000,0,NaN,audi,nein
156,6799,control,kleinwagen,2009,NaN,60,NaN,20000,5,benzin,volkswagen,nein
165,500,control,kleinwagen,1999,manuell,0,NaN,150000,0,benzin,renault,nein
166,1495,control,kombi,2001,NaN,64,NaN,150000,9,diesel,volkswagen,NaN
191,14000,test,limousine,2008,NaN,235,NaN,150000,0,NaN,bmw,nein
199,1200,test,coupe,1990,manuell,45,NaN,150000,0,benzin,volkswagen,NaN
268,450,control,NaN,2016,manuell,0,NaN,150000,3,benzin,mitsubishi,nein
285,1500,control,coupe,1994,manuell,116,NaN,150000,8,NaN,audi,nein
318,200,control,NaN,2009,NaN,0,NaN,10000,0,NaN,sonstige_autos,NaN
320,1600,test,kombi,1999,manuell,0,NaN,150000,6,benzin,bmw,nein
365,5500,test,kleinwagen,2012,manuell,68,NaN,40000,12,NaN,peugeot,nein
373,300,control,kleinwagen,2001,manuell,0,NaN,150000,5,benzin,peugeot,ja
376,49500,test,cabrio,2013,NaN,0,NaN,10000,6,benzin,sonstige_autos,nein
427,13950,control,andere,2011,manuell,140,NaN,60000,11,diesel,alfa_romeo,nein
446,3950,test,kleinwagen,2004,automatik,5,NaN,70000,5,diesel,sonstige_autos,nein
450,1300,control,NaN,2017,manuell,150,NaN,150000,10,NaN,volkswagen,nein
451,5800,control,bus,2007,manuell,105,NaN,150000,11,diesel,volkswagen,ja
458,1950,control,NaN,2017,manuell,0,NaN,150000,7,benzin,volkswagen,nein
563,2600,control,NaN,2005,NaN,0,NaN,125000,0,NaN,chevrolet,NaN
577,50,test,NaN,1985,NaN,0,NaN,150000,11,NaN,trabant,NaN
612,3800,test,cabrio,2005,manuell,109,NaN,100000,12,benzin,peugeot,NaN
644,1600,test,kleinwagen,2002,manuell,64,NaN,150000,2,benzin,volkswagen,nein
658,7400,test,cabrio,2003,automatik,192,NaN,150000,8,NaN,bmw,nein
672,2200,test,limousine,1995,automatik,299,NaN,150000,5,NaN,audi,ja
677,1900,control,limousine,2000,manuell,125,NaN,150000,5,benzin,mitsubishi,nein
678,15000,test,coupe,1971,NaN,0,NaN,5000,4,NaN,sonstige_autos,nein
690,9900,test,suv,2000,automatik,250,NaN,150000,4,lpg,sonstige_autos,nein
698,5900,control,kombi,2004,manuell,150,NaN,150000,2,diesel,mercedes_benz,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
370819,400,control,kombi,1998,manuell,105,NaN,150000,7,benzin,volvo,NaN
370836,900,control,NaN,2017,manuell,101,NaN,150000,6,NaN,opel,NaN
370890,250,control,kleinwagen,1997,manuell,66,NaN,150000,5,benzin,sonstige_autos,NaN
370903,650,test,NaN,2000,manuell,150,NaN,150000,7,NaN,audi,nein
370952,9800,control,kleinwagen,2013,manuell,90,NaN,50000,4,NaN,renault,NaN
370968,11690,control,kombi,2005,automatik,224,NaN,150000,5,diesel,audi,nein
371001,2800,control,coupe,2003,manuell,163,NaN,150000,7,benzin,citroen,NaN
371004,5000,test,limousine,2006,manuell,175,NaN,125000,12,benzin,sonstige_autos,nein
371029,7900,test,bus,2009,NaN,140,NaN,125000,7,diesel,sonstige_autos,nein
371060,2200,test,suv,1994,manuell,124,NaN,150000,0,benzin,ford,nein
371065,18500,test,limousine,2009,automatik,190,NaN,150000,10,diesel,audi,nein
371099,200,control,NaN,1910,NaN,0,NaN,5000,0,benzin,sonstige_autos,NaN
371102,1599,test,kleinwagen,2002,manuell,75,NaN,150000,0,benzin,ford,NaN
371110,1670,control,NaN,2018,manuell,0,NaN,90000,0,benzin,renault,nein
371121,1500,control,bus,1984,manuell,0,NaN,150000,5,diesel,mercedes_benz,NaN
371146,10980,test,NaN,2018,manuell,75,NaN,20000,1,NaN,volkswagen,nein
371150,1000,control,NaN,2017,manuell,54,NaN,125000,2,NaN,hyundai,nein
371196,42000,control,limousine,2012,automatik,564,NaN,50000,3,benzin,sonstige_autos,nein
371203,6000,test,kleinwagen,2008,manuell,155,NaN,150000,5,benzin,sonstige_autos,nein
371214,30900,control,cabrio,1960,automatik,250,NaN,100000,7,benzin,sonstige_autos,nein
371216,1750,test,NaN,1995,NaN,0,NaN,100000,12,NaN,sonstige_autos,NaN
371220,200,control,kleinwagen,1998,manuell,37,NaN,150000,4,benzin,volkswagen,ja
371223,4300,test,kleinwagen,2008,automatik,0,NaN,150000,3,NaN,honda,NaN
371309,1500,control,NaN,1995,NaN,0,NaN,150000,0,NaN,volkswagen,NaN
371388,5000,control,limousine,2002,automatik,170,NaN,150000,0,benzin,audi,nein
371399,560,control,kleinwagen,2001,automatik,170,NaN,90000,0,benzin,fiat,ja
371476,9400,control,kombi,2007,manuell,200,NaN,150000,4,diesel,sonstige_autos,ja
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371509,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [18]:
# verificando qual é o modelo que mais aparece
base.model.value_counts()

golf                  28989
andere                25560
3er                   19905
polo                  12604
corsa                 12149
astra                 10458
a4                     9972
passat                 9966
c_klasse               8624
5er                    8304
e_klasse               7379
a3                     6498
a6                     5832
focus                  5805
fiesta                 5645
transporter            5371
twingo                 4804
2_reihe                4753
fortwo                 4286
a_klasse               4241
vectra                 4072
1er                    3818
mondeo                 3503
touran                 3492
clio                   3456
3_reihe                3427
punto                  3238
zafira                 2983
megane                 2809
ibiza                  2634
                      ...
mii                      81
crossfire                66
range_rover_evoque       65
gl                       63
nubira                   61
move                     51
lybra                    50
v60                      48
145                      45
croma                    45
amarok                   39
delta                    39
lodgy                    35
terios                   35
9000                     28
charade                  27
b_max                    26
musa                     23
materia                  18
200                      17
kappa                    15
samara                   12
elefantino               11
i3                       10
kalina                    9
serie_2                   8
rangerover                6
serie_3                   3
serie_1                   1
discovery_sport           1
Name: model, Length: 251, dtype: int64

In [19]:
# verificando os nulos para fuelType
base.loc[base.fuelType.isnull()]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
9,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN
13,2500,control,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein
26,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein
36,1600,control,andere,1991,manuell,75,kadett,70000,0,NaN,opel,NaN
41,7500,control,limousine,2002,automatik,306,e_klasse,150000,4,NaN,mercedes_benz,NaN
52,1400,control,NaN,2016,manuell,55,andere,5000,1,NaN,hyundai,NaN
54,4700,control,kombi,2005,manuell,0,signum,150000,0,NaN,opel,nein
58,2399,test,NaN,2018,manuell,64,andere,125000,3,NaN,seat,nein
66,10900,test,NaN,2017,manuell,101,astra,50000,3,NaN,opel,nein
70,1200,test,coupe,2001,NaN,0,astra,150000,0,NaN,opel,NaN
72,2300,control,NaN,1997,manuell,150,5er,150000,3,NaN,bmw,nein
83,350,control,kleinwagen,1997,manuell,54,NaN,150000,3,NaN,fiat,ja
94,250,control,NaN,2000,NaN,60,ka,150000,0,NaN,ford,NaN
96,8390,test,NaN,2009,NaN,0,insignia,150000,0,NaN,opel,NaN
99,6450,test,bus,2008,manuell,84,transporter,150000,12,NaN,volkswagen,nein
108,300,test,cabrio,1992,manuell,105,escort,150000,0,NaN,ford,ja
123,400,control,limousine,2000,manuell,144,omega,150000,10,NaN,opel,ja
134,3390,test,NaN,2000,NaN,0,3er,150000,2,NaN,bmw,NaN
139,1450,control,limousine,1992,manuell,136,NaN,150000,0,NaN,audi,nein
147,1500,test,kombi,1996,manuell,126,a4,150000,0,NaN,audi,nein
152,300,control,NaN,2005,manuell,0,punto,40000,9,NaN,fiat,ja
164,1499,test,kleinwagen,2002,manuell,140,a_klasse,150000,10,NaN,mercedes_benz,nein
168,1200,control,NaN,2018,manuell,75,astra,150000,0,NaN,opel,nein
191,14000,test,limousine,2008,NaN,235,NaN,150000,0,NaN,bmw,nein
202,2800,control,NaN,2018,manuell,75,twingo,125000,12,NaN,renault,nein
221,1000,test,kombi,1999,manuell,165,a6,150000,0,NaN,audi,NaN
233,1600,test,kombi,2000,manuell,90,cordoba,150000,11,NaN,seat,nein
240,3750,control,NaN,2005,NaN,75,golf,150000,0,NaN,volkswagen,NaN
245,130,test,kombi,1998,NaN,0,e_klasse,150000,0,NaN,mercedes_benz,NaN
256,8000,test,limousine,2006,manuell,177,impreza,150000,0,NaN,subaru,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
371174,700,test,kleinwagen,1997,manuell,60,polo,150000,0,NaN,volkswagen,NaN
371175,1500,control,kleinwagen,1998,manuell,75,golf,150000,12,NaN,volkswagen,NaN
371177,10500,test,cabrio,1968,manuell,54,andere,20000,4,NaN,renault,nein
371181,3590,control,coupe,2000,NaN,0,3er,150000,10,NaN,bmw,nein
371189,350,test,NaN,2000,manuell,50,ibiza,150000,5,NaN,seat,nein
371216,1750,test,NaN,1995,NaN,0,NaN,100000,12,NaN,sonstige_autos,NaN
371223,4300,test,kleinwagen,2008,automatik,0,NaN,150000,3,NaN,honda,NaN
371274,400,test,NaN,2000,NaN,0,twingo,150000,0,NaN,renault,NaN
371286,1000,control,NaN,2017,manuell,101,a4,150000,9,NaN,audi,NaN
371287,999,test,kombi,1997,manuell,170,5er,150000,6,NaN,bmw,nein
371309,1500,control,NaN,1995,NaN,0,NaN,150000,0,NaN,volkswagen,NaN
371323,1999,test,kleinwagen,2002,manuell,75,golf,150000,0,NaN,volkswagen,NaN
371342,5000,control,coupe,1999,automatik,0,3er,150000,0,NaN,bmw,NaN
371349,1350,test,NaN,2016,manuell,0,clk,150000,8,NaN,mercedes_benz,ja
371354,2140,test,NaN,2018,manuell,80,fiesta,150000,6,NaN,ford,nein
371378,240,control,kleinwagen,1995,manuell,75,polo,150000,7,NaN,volkswagen,NaN
371380,9000,test,NaN,2008,NaN,0,1er,125000,0,NaN,bmw,NaN
371390,1799,test,kombi,2005,manuell,180,signum,150000,1,NaN,opel,ja
371414,399,test,andere,1994,NaN,1103,3er,150000,0,NaN,bmw,NaN
371419,3000,control,limousine,2001,automatik,150,a4,150000,8,NaN,audi,ja
371444,5000,control,NaN,2017,manuell,120,andere,150000,7,NaN,citroen,ja
371460,3500,control,NaN,1995,NaN,0,polo,150000,0,NaN,volkswagen,NaN
371482,1300,control,kleinwagen,1999,manuell,75,2_reihe,125000,0,NaN,peugeot,NaN
371484,2999,test,kombi,2004,manuell,234,vectra,100000,1,NaN,opel,NaN
371486,350,control,kleinwagen,1996,NaN,65,punto,150000,0,NaN,fiat,NaN
371496,3850,test,cabrio,2006,manuell,108,2_reihe,125000,2,NaN,peugeot,nein
371504,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN
371509,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein
371519,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [20]:
base.fuelType.value_counts()

benzin     217582
diesel     106002
lpg          5222
cng           557
hybrid        271
andere        165
elektro       101
Name: fuelType, dtype: int64

In [21]:
base.loc[pd.isnull(base.notRepairedDamage)]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
2,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN
8,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN
9,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN
12,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN
15,450,test,kleinwagen,1910,NaN,0,ka,5000,0,benzin,ford,NaN
16,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN
31,899,control,NaN,2016,manuell,60,clio,150000,6,benzin,renault,NaN
36,1600,control,andere,1991,manuell,75,kadett,70000,0,NaN,opel,NaN
41,7500,control,limousine,2002,automatik,306,e_klasse,150000,4,NaN,mercedes_benz,NaN
42,12500,test,limousine,2006,automatik,231,5er,150000,11,diesel,bmw,NaN
44,3900,test,kleinwagen,2008,automatik,61,fortwo,80000,6,benzin,smart,NaN
48,7750,control,NaN,2017,manuell,80,golf,100000,1,benzin,volkswagen,NaN
50,14800,control,cabrio,2008,manuell,170,1er,125000,4,benzin,bmw,NaN
52,1400,control,NaN,2016,manuell,55,andere,5000,1,NaN,hyundai,NaN
53,7999,control,limousine,2008,automatik,143,3er,150000,12,diesel,bmw,NaN
61,200,test,coupe,1995,manuell,102,3er,150000,4,benzin,bmw,NaN
69,1280,control,limousine,1992,automatik,109,andere,150000,9,benzin,mercedes_benz,NaN
70,1200,test,coupe,2001,NaN,0,astra,150000,0,NaN,opel,NaN
78,800,test,NaN,2000,manuell,90,golf,150000,2,diesel,volkswagen,NaN
87,8000,test,suv,2005,manuell,185,xc_reihe,150000,8,diesel,volvo,NaN
92,2400,test,limousine,2003,manuell,0,a4,150000,9,diesel,audi,NaN
93,1222,control,limousine,1984,automatik,180,andere,150000,3,benzin,opel,NaN
94,250,control,NaN,2000,NaN,60,ka,150000,0,NaN,ford,NaN
96,8390,test,NaN,2009,NaN,0,insignia,150000,0,NaN,opel,NaN
103,499,control,limousine,1995,manuell,101,a4,150000,5,benzin,audi,NaN
105,6500,test,limousine,2004,manuell,163,a4,150000,4,diesel,audi,NaN
107,650,test,limousine,1997,automatik,102,3er,150000,8,benzin,bmw,NaN
111,900,test,NaN,1995,manuell,90,civic,150000,3,benzin,honda,NaN
114,350,test,kleinwagen,1998,NaN,0,corsa,150000,2,benzin,opel,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371414,399,test,andere,1994,NaN,1103,3er,150000,0,NaN,bmw,NaN
371416,700,test,kombi,1997,manuell,145,galaxy,150000,6,benzin,ford,NaN
371418,4700,test,bus,2004,manuell,101,touran,150000,2,diesel,volkswagen,NaN
371420,399,control,kleinwagen,1992,manuell,45,polo,150000,4,benzin,volkswagen,NaN
371422,1599,control,kombi,2002,manuell,101,astra,150000,9,benzin,opel,NaN
371424,9000,control,kombi,2005,manuell,0,a6,150000,0,diesel,audi,NaN
371443,3300,control,kombi,2006,NaN,0,touran,150000,7,diesel,volkswagen,NaN
371445,2500,control,kleinwagen,2007,manuell,60,andere,125000,3,benzin,hyundai,NaN
371448,480,test,limousine,1996,manuell,136,c_klasse,150000,6,benzin,mercedes_benz,NaN
371450,1500,test,limousine,1991,manuell,94,e_klasse,150000,10,diesel,mercedes_benz,NaN
371452,400,test,kombi,1996,manuell,150,a4,150000,0,benzin,audi,NaN
371454,5800,test,kombi,2003,manuell,168,a6,150000,4,diesel,audi,NaN
371457,5990,control,bus,1984,automatik,0,andere,70000,4,benzin,chevrolet,NaN
371460,3500,control,NaN,1995,NaN,0,polo,150000,0,NaN,volkswagen,NaN
371473,400,control,kombi,1991,manuell,0,legacy,150000,0,benzin,subaru,NaN
371475,1500,control,limousine,1999,manuell,75,golf,150000,4,benzin,volkswagen,NaN
371482,1300,control,kleinwagen,1999,manuell,75,2_reihe,125000,0,NaN,peugeot,NaN
371484,2999,test,kombi,2004,manuell,234,vectra,100000,1,NaN,opel,NaN
371485,4200,control,limousine,2001,automatik,193,5er,150000,1,diesel,bmw,NaN
371486,350,control,kleinwagen,1996,NaN,65,punto,150000,0,NaN,fiat,NaN
371493,3299,test,NaN,2005,automatik,0,outlander,150000,4,benzin,mitsubishi,NaN
371494,11500,control,limousine,2004,automatik,445,7er,125000,0,benzin,bmw,NaN
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371498,699,control,limousine,1999,manuell,101,vectra,150000,3,benzin,opel,NaN
371504,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN
371507,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN
371514,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN
371515,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN
371526,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN

In [22]:
base.notRepairedDamage.value_counts()

nein    259301
ja       34004
Name: notRepairedDamage, dtype: int64

### Agora vamos preencher os valores faltantes ###

In [23]:
# criando um dicionário para os valores que quero injetar
valores = {'vehicleType':'limousine','gearbox':'manuell','model':'golf','fuelType':'benzin','notRepairedDamage':'nein'}

In [24]:
# injetando os valores nos valores nulos
base = base.fillna(value = valores)

## Agora sim vamos para a previsão

In [25]:
previsores = base.iloc[:,1:13].values

In [26]:
preco_real = base.iloc[:,0].values

### tranformando os valores catégoricos para númericos

In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
labelencoder_previsores = LabelEncoder()

In [29]:
previsores[:,0] = labelencoder_previsores.fit_transform(previsores[:,0])
previsores[:,1] = labelencoder_previsores.fit_transform(previsores[:,1])
previsores[:,3] = labelencoder_previsores.fit_transform(previsores[:,3])
previsores[:,5] = labelencoder_previsores.fit_transform(previsores[:,5])
previsores[:,8] = labelencoder_previsores.fit_transform(previsores[:,8])
previsores[:,9] = labelencoder_previsores.fit_transform(previsores[:,9])
previsores[:,10] = labelencoder_previsores.fit_transform(previsores[:,10])

In [30]:
previsores

array([[1, 6, 1993, ..., 1, 38, 1],
       [1, 3, 2011, ..., 3, 1, 0],
       [1, 7, 2004, ..., 3, 14, 1],
       ...,
       [1, 1, 1996, ..., 3, 38, 1],
       [1, 5, 2002, ..., 3, 38, 1],
       [0, 6, 2013, ..., 1, 2, 1]], dtype=object)

### One hot encoder => é a criação de variáveis do tipo Dummy, o tipo de dados Dummy só devem ser usados em dados categóricos que não tenham prioridade, por exemplo o tipo de câmbio, manual ou automatico, não sabemos qual dos dois é o melhor ###

In [31]:
from sklearn.preprocessing import OneHotEncoder

In [32]:
oneHotEncoder = OneHotEncoder(categorical_features= [0,1,3,5,8,9,10])

In [33]:
previsores = oneHotEncoder.fit_transform(previsores).toarray()

In [34]:
previsores.shape

(359291, 316)

### criando a rede neural ###

In [35]:
from keras.layers import Dense
from keras.models import Sequential

/home/alison/.pyenv/versions/anaconda3-5.2.0/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

In [38]:
regressor = Sequential()
# 1ª camada oculta, com 316 entradas
regressor.add(Dense(units = 158, activation= 'relu', input_dim = 316))

# 2ª camada oculta
regressor.add(Dense(units = 158, activation= 'relu'))

# camada de saída, vai gerar somente um número de saída, então só terá uma saída
# e a função linear não altera o valor de saída
regressor.add(Dense(units = 1, activation= 'linear'))

regressor.compile(loss = 'mean_absolute_error', optimizer = 'adam', metrics = ['mean_absolute_error'])

In [39]:
regressor.fit(previsores, preco_real, batch_size=300, epochs = 100)

Epoch 1/100
359291/359291 [==============================] - 5s 15us/step - loss: 3888.0445 - mean_absolute_error: 3888.0445
Epoch 2/100
359291/359291 [==============================] - 5s 14us/step - loss: 3468.2787 - mean_absolute_error: 3468.2787
Epoch 3/100
359291/359291 [==============================] - 5s 14us/step - loss: 3292.0960 - mean_absolute_error: 3292.0960
Epoch 4/100
359291/359291 [==============================] - 5s 14us/step - loss: 3000.2226 - mean_absolute_error: 3000.2226
Epoch 5/100
359291/359291 [==============================] - 5s 14us/step - loss: 2832.4692 - mean_absolute_error: 2832.4692
Epoch 6/100
359291/359291 [==============================] - 5s 15us/step - loss: 2747.8367 - mean_absolute_error: 2747.8367
Epoch 7/100
359291/359291 [==============================] - 5s 15us/step - loss: 2720.1518 - mean_absolute_error: 2720.1518
Epoch 8/100
359291/359291 [==============================] - 5s 15us/step - loss: 2686.1184 - mean_absolute_error: 2686.1184
Epoch 9/100
359291/359291 [==============================] - 5s 15us/step - loss: 2636.2540 - mean_absolute_error: 2636.2540
Epoch 10/100
359291/359291 [==============================] - 5s 15us/step - loss: 2599.0505 - mean_absolute_error: 2599.0505
Epoch 11/100
359291/359291 [==============================] - 5s 15us/step - loss: 2568.3310 - mean_absolute_error: 2568.3310
Epoch 12/100
359291/359291 [==============================] - 5s 15us/step - loss: 2533.6351 - mean_absolute_error: 2533.6351
Epoch 13/100
359291/359291 [==============================] - 6s 15us/step - loss: 2493.6439 - mean_absolute_error: 2493.6439
Epoch 14/100
359291/359291 [==============================] - 5s 15us/step - loss: 2480.5281 - mean_absolute_error: 2480.5281
Epoch 15/100
359291/359291 [==============================] - 5s 15us/step - loss: 2473.6369 - mean_absolute_error: 2473.6369
Epoch 16/100
359291/359291 [==============================] - 5s 15us/step - loss: 2436.0483 - mean_absolute_error: 2436.0483
Epoch 17/100
359291/359291 [==============================] - 5s 15us/step - loss: 2446.2654 - mean_absolute_error: 2446.2654
Epoch 18/100
359291/359291 [==============================] - 5s 15us/step - loss: 2444.1569 - mean_absolute_error: 2444.1569
Epoch 19/100
359291/359291 [==============================] - 5s 15us/step - loss: 2429.4817 - mean_absolute_error: 2429.4817
Epoch 20/100
359291/359291 [==============================] - 5s 15us/step - loss: 2430.9396 - mean_absolute_error: 2430.9396
Epoch 21/100
359291/359291 [==============================] - 6s 15us/step - loss: 2404.9339 - mean_absolute_error: 2404.9339
Epoch 22/100
359291/359291 [==============================] - 6s 15us/step - loss: 2402.3263 - mean_absolute_error: 2402.3263
Epoch 23/100
359291/359291 [==============================] - 5s 15us/step - loss: 2399.8013 - mean_absolute_error: 2399.8013
Epoch 24/100
359291/359291 [==============================] - 5s 15us/step - loss: 2395.4270 - mean_absolute_error: 2395.4270
Epoch 25/100
359291/359291 [==============================] - 5s 15us/step - loss: 2390.7282 - mean_absolute_error: 2390.7282
Epoch 26/100
359291/359291 [==============================] - 5s 15us/step - loss: 2385.4961 - mean_absolute_error: 2385.4961
Epoch 27/100
359291/359291 [==============================] - 5s 15us/step - loss: 2372.8740 - mean_absolute_error: 2372.8740
Epoch 28/100
359291/359291 [==============================] - 5s 15us/step - loss: 2378.3075 - mean_absolute_error: 2378.3075
Epoch 29/100
359291/359291 [==============================] - 6s 16us/step - loss: 2366.0689 - mean_absolute_error: 2366.0689
Epoch 30/100
359291/359291 [==============================] - 5s 15us/step - loss: 2362.1173 - mean_absolute_error: 2362.1173
Epoch 31/100
359291/359291 [==============================] - 6s 16us/step - loss: 2361.3642 - mean_absolute_error: 2361.3642
Epoch 32/100
359291/359291 [==============================] - 5s 15us/step - loss: 2346.6994 - mean_absolute_error: 2346.6994
Epoch 33/100
359291/359291 [==============================] - 5s 15us/step - loss: 2353.8194 - mean_absolute_error: 2353.8194
Epoch 34/100
359291/359291 [==============================] - 5s 15us/step - loss: 2346.9295 - mean_absolute_error: 2346.9295
Epoch 35/100
359291/359291 [==============================] - 5s 15us/step - loss: 2359.7228 - mean_absolute_error: 2359.7228
Epoch 36/100
359291/359291 [==============================] - 5s 15us/step - loss: 2356.6453 - mean_absolute_error: 2356.6453
Epoch 37/100
359291/359291 [==============================] - 5s 15us/step - loss: 2351.2785 - mean_absolute_error: 2351.2785
Epoch 38/100
359291/359291 [==============================] - 5s 15us/step - loss: 2342.9402 - mean_absolute_error: 2342.9402
Epoch 39/100
359291/359291 [==============================] - 5s 15us/step - loss: 2329.8190 - mean_absolute_error: 2329.8190
Epoch 40/100
359291/359291 [==============================] - 5s 15us/step - loss: 2331.0663 - mean_absolute_error: 2331.0663
Epoch 41/100
359291/359291 [==============================] - 5s 15us/step - loss: 2331.9708 - mean_absolute_error: 2331.9708
Epoch 42/100
359291/359291 [==============================] - 6s 17us/step - loss: 2315.9185 - mean_absolute_error: 2315.9185
Epoch 43/100
359291/359291 [==============================] - 6s 15us/step - loss: 2329.2226 - mean_absolute_error: 2329.2226
Epoch 44/100
359291/359291 [==============================] - 6s 15us/step - loss: 2311.3044 - mean_absolute_error: 2311.3044
Epoch 45/100
359291/359291 [==============================] - 5s 15us/step - loss: 2313.0756 - mean_absolute_error: 2313.0756
Epoch 46/100
359291/359291 [==============================] - 5s 15us/step - loss: 2312.5917 - mean_absolute_error: 2312.5917
Epoch 47/100
359291/359291 [==============================] - 5s 15us/step - loss: 2308.8814 - mean_absolute_error: 2308.8814
Epoch 48/100
359291/359291 [==============================] - 5s 15us/step - loss: 2306.4181 - mean_absolute_error: 2306.4181
Epoch 49/100
359291/359291 [==============================] - 5s 15us/step - loss: 2312.9154 - mean_absolute_error: 2312.9154
Epoch 50/100
359291/359291 [==============================] - 5s 15us/step - loss: 2299.7562 - mean_absolute_error: 2299.7562
Epoch 51/100
359291/359291 [==============================] - 5s 15us/step - loss: 2305.6520 - mean_absolute_error: 2305.6520
Epoch 52/100
359291/359291 [==============================] - 5s 15us/step - loss: 2294.1410 - mean_absolute_error: 2294.1410
Epoch 53/100
359291/359291 [==============================] - 5s 15us/step - loss: 2310.6608 - mean_absolute_error: 2310.6608
Epoch 54/100
359291/359291 [==============================] - 5s 15us/step - loss: 2308.0748 - mean_absolute_error: 2308.0748
Epoch 55/100
359291/359291 [==============================] - 5s 15us/step - loss: 2297.5183 - mean_absolute_error: 2297.5183
Epoch 56/100
359291/359291 [==============================] - 5s 15us/step - loss: 2303.3573 - mean_absolute_error: 2303.3573
Epoch 57/100
359291/359291 [==============================] - 5s 15us/step - loss: 2295.6485 - mean_absolute_error: 2295.6485
Epoch 58/100
359291/359291 [==============================] - 5s 15us/step - loss: 2286.6066 - mean_absolute_error: 2286.6066
Epoch 59/100
359291/359291 [==============================] - 6s 16us/step - loss: 2291.8980 - mean_absolute_error: 2291.8980
Epoch 60/100
359291/359291 [==============================] - 6s 15us/step - loss: 2294.6874 - mean_absolute_error: 2294.6874
Epoch 61/100
359291/359291 [==============================] - 6s 15us/step - loss: 2296.5436 - mean_absolute_error: 2296.5436
Epoch 62/100
359291/359291 [==============================] - 5s 15us/step - loss: 2280.9877 - mean_absolute_error: 2280.9877
Epoch 63/100
359291/359291 [==============================] - 5s 15us/step - loss: 2281.7168 - mean_absolute_error: 2281.7168
Epoch 64/100
359291/359291 [==============================] - 5s 15us/step - loss: 2273.1830 - mean_absolute_error: 2273.1830
Epoch 65/100
359291/359291 [==============================] - 5s 15us/step - loss: 2283.6899 - mean_absolute_error: 2283.6899
Epoch 66/100

359291/359291 [==============================] - 5s 14us/step - loss: 2283.4383 - mean_absolute_error: 2283.4383
Epoch 67/100
359291/359291 [==============================] - 5s 14us/step - loss: 2275.4802 - mean_absolute_error: 2275.4802
Epoch 68/100
359291/359291 [==============================] - 5s 15us/step - loss: 2275.5093 - mean_absolute_error: 2275.5093
Epoch 69/100
359291/359291 [==============================] - 5s 15us/step - loss: 2279.5016 - mean_absolute_error: 2279.5016
Epoch 70/100
359291/359291 [==============================] - 5s 15us/step - loss: 2268.7444 - mean_absolute_error: 2268.7444
Epoch 71/100
359291/359291 [==============================] - 5s 15us/step - loss: 2268.7705 - mean_absolute_error: 2268.7705
Epoch 72/100
359291/359291 [==============================] - 5s 15us/step - loss: 2274.4984 - mean_absolute_error: 2274.4984
Epoch 73/100
359291/359291 [==============================] - 5s 15us/step - loss: 2277.9316 - mean_absolute_error: 2277.9316
Epoch 74/100
359291/359291 [==============================] - 5s 15us/step - loss: 2272.3085 - mean_absolute_error: 2272.3085
Epoch 75/100
359291/359291 [==============================] - 5s 15us/step - loss: 2249.5486 - mean_absolute_error: 2249.5486
Epoch 76/100
359291/359291 [==============================] - 5s 15us/step - loss: 2255.2364 - mean_absolute_error: 2255.2364
Epoch 77/100
359291/359291 [==============================] - 6s 16us/step - loss: 2251.9260 - mean_absolute_error: 2251.9260
Epoch 78/100
359291/359291 [==============================] - 6s 18us/step - loss: 2261.2105 - mean_absolute_error: 2261.2105
Epoch 79/100
359291/359291 [==============================] - 6s 17us/step - loss: 2258.9593 - mean_absolute_error: 2258.9593
Epoch 80/100
359291/359291 [==============================] - 6s 17us/step - loss: 2254.9946 - mean_absolute_error: 2254.9946
Epoch 81/100
359291/359291 [==============================] - 6s 17us/step - loss: 2263.9437 - mean_absolute_error: 2263.9437
Epoch 82/100
359291/359291 [==============================] - 5s 15us/step - loss: 2253.3193 - mean_absolute_error: 2253.3193
Epoch 83/100
359291/359291 [==============================] - 5s 15us/step - loss: 2252.2252 - mean_absolute_error: 2252.2252
Epoch 84/100
359291/359291 [==============================] - 5s 14us/step - loss: 2260.4802 - mean_absolute_error: 2260.4802
Epoch 85/100
359291/359291 [==============================] - 5s 14us/step - loss: 2256.8157 - mean_absolute_error: 2256.8157
Epoch 86/100
359291/359291 [==============================] - 5s 15us/step - loss: 2245.1485 - mean_absolute_error: 2245.1485
Epoch 87/100
359291/359291 [==============================] - 5s 14us/step - loss: 2247.0231 - mean_absolute_error: 2247.0231
Epoch 88/100
359291/359291 [==============================] - 5s 14us/step - loss: 2240.7268 - mean_absolute_error: 2240.7268
Epoch 89/100
359291/359291 [==============================] - 5s 14us/step - loss: 2230.5966 - mean_absolute_error: 2230.5966
Epoch 90/100
359291/359291 [==============================] - 5s 14us/step - loss: 2244.2878 - mean_absolute_error: 2244.2878
Epoch 91/100
359291/359291 [==============================] - 5s 14us/step - loss: 2246.9387 - mean_absolute_error: 2246.9387
Epoch 92/100
359291/359291 [==============================] - 5s 14us/step - loss: 2240.8442 - mean_absolute_error: 2240.8442
Epoch 93/100
359291/359291 [==============================] - 5s 14us/step - loss: 2240.8208 - mean_absolute_error: 2240.8208
Epoch 94/100
359291/359291 [==============================] - 5s 14us/step - loss: 2240.9566 - mean_absolute_error: 2240.9566
Epoch 95/100
359291/359291 [==============================] - 5s 15us/step - loss: 2238.2613 - mean_absolute_error: 2238.2613
Epoch 96/100
359291/359291 [==============================] - 5s 15us/step - loss: 2230.6337 - mean_absolute_error: 2230.6337
Epoch 97/100
359291/359291 [==============================] - 5s 14us/step - loss: 2236.0071 - mean_absolute_error: 2236.0071
Epoch 98/100
359291/359291 [==============================] - 5s 14us/step - loss: 2235.1644 - mean_absolute_error: 2235.1644
Epoch 99/100
359291/359291 [==============================] - 5s 15us/step - loss: 2232.2651 - mean_absolute_error: 2232.2651
Epoch 100/100
359291/359291 [==============================] - 5s 14us/step - loss: 2239.1428 - mean_absolute_error: 2239.1428

In [40]:
previsoes = regressor.predict(previsores)

In [41]:
preco_real.mean()

5916.833945186492

In [44]:
previsoes[:10]

array([[  476.80206],
       [ 9565.123  ],
       [11647.177  ],
       [ 1128.7189 ],
       [ 5380.2354 ],
       [  757.9741 ],
       [ 1907.9701 ],
       [13373.59   ],
       [ 1367.2845 ],
       [ 1088.1676 ]], dtype=float32)

In [45]:
preco_real[:10]

array([  480, 18300,  9800,  1500,  3600,   650,  2200, 14500,   999,
        2000])